### ISSUE TITLE
ERROR: Makepkg was unable to build openwmail

### ISSUE THREAD

**Issue by smed79** [openWMail/openWMail#50]
* Which Operating System are you using?

```
Manjaro Linux 17.1.11 (Hakoila) / Xfce 4.12
```
* Issue

Makepkg was unable to build openwmail

```
make: *** [nodehun.target.mk:108: Release/obj.target/nodehun/src/nodehun.o] Error 1
make : on quitte le répertoire « /tmp/yaourt-tmp-moi/aur-openwmail/src/openWMail-1.0.0/bin/app/node_modules/nodehun/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.14.57-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/yaourt-tmp-moi/aur-openwmail/src/openWMail-1.0.0/bin/app/node_modules/nodehun
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodehun@2.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moi/.npm/_logs/2018-07-24T17_51_45_437Z-debug.log
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
==> ERREUR : Makepkg n'a pas pu construire openwmail.
```

- logs
[yaourt](https://github.com/openWMail/openWMail/files/2232414/yaourt.log)
[npm](https://github.com/openWMail/openWMail/files/2232417/npm.log)

---
*ps* : for who want to find a clean consistent system after the failted installation, here is the command to execute in the terminal 
```
sudo pacman -Rsn c-ares http-parser libuv node-gyp nodejs semver npm electron
```
then delete these folders
```
/home/<user>/.electron/
/home/<user>/.npm/
/home/<user>/.config/configstore/update-notifier-npm.json
/home/<user>/.local/share/openwmail/
/home/<user>/.node-gyp/
```

**Comment by geekgonecrazy** [comment]
hm.. looks like a library build error with `nodehun` they might have updated the package.  Might have to swap it out to make use of one of the other compiled instead of from source :(
